### ISSUE TITLE
How can I specify graphviz rendering parameters to rdfdot

### ISSUE THREAD

**Issue by rchateauneu** [nichtich/RDF-Trine-Exporter-GraphViz#1]
Hi,

I would like when using rdfdot, to specify rendering parameters to graphviz as on the command line:
http://www.graphviz.org/doc/info/command.html

For example the type of layout, the font etc...

Thanks

**Comment by nichtich** [comment]
Simply passing graphviz parameters to `dot` won't work because the [internal Perl wrapper](https://metacpan.org/pod/GraphViz) seems to not support passing graphviz options. The best method is to let rdfdot produce the `dot` file and transform in with graphviz.

```
rdfdot $rdffile | dot $dotoptions
```

**Comment by rchateauneu** [comment]
Many thanks Jakob, and thanks to have put the answer on stackoverflow too.

Best regards

Remi
